'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class WOAIHavester

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblTitleOaiHavester control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleOaiHavester As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHeadResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeadResult As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkOAI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkOAI As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblHeadDes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeadDes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblURLH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblURLH As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblURLReVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblURLReVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVerbH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVerbH As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVerbVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVerbVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReponseH control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReponseH As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblResponseVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblResponseVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDES control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDES As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorCodeval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorCodeval As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblErrorDetailVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorDetailVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblXML As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblToltalRec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblToltalRec As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblToltalRecVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblToltalRecVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentRec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentRec As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentRecVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentRecVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkNextRec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkNextRec As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblrepositoryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrepositoryName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblrepositoryNameVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrepositoryNameVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblbaseURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblbaseURL As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblbaseURLVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblbaseURLVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblprotocolVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblprotocolVersion As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblprotocolVersionVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblprotocolVersionVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbladminEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbladminEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbladminEmailVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbladminEmailVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblearliestDatestamp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblearliestDatestamp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblearliestDatestampVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblearliestDatestampVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldeleteRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldeleteRecord As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldeleteRecordVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldeleteRecordVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblgranularity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblgranularity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblgranularityVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblgranularityVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcompression control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcompression As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcompressionVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcompressionVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldescriptionVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldescriptionVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbloai_identifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbloai_identifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblscheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblscheme As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblschemeVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblschemeVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblrepositoryIdentifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrepositoryIdentifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblrepositoryIdentifierVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrepositoryIdentifierVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldelimiter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldelimiter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldelimiterVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldelimiterVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblsampleIdentifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblsampleIdentifier As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblsampleIdentifierVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblsampleIdentifierVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcontent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcontent As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblURLCon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblURLCon As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblURLConVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblURLConVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTextCon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTextCon As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTextConVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTextConVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcollectionIcon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcollectionIcon As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblurlCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblurlCol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblurlColVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblurlColVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLinkCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkCol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLinkColVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLinkColVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitleCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleCol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitleColVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleColVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWidthCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWidthCol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWidthColVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWidthColVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHeightCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeightCol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblHeightColVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeightColVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblmetadataRendering control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblmetadataRendering As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblmetadataRenderingVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblmetadataRenderingVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dtgListIdentifiers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtgListIdentifiers As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''dtgListMetadataFormats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtgListMetadataFormats As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblListSet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblListSet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dtgListSets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtgListSets As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblListRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblListRecord As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitleVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAuthorVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthorVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDescriptionSet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescriptionSet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDescriptionSetVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescriptionSetVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTypeVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcoverage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcoverage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcoverageVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcoverageVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubjectVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubjectVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcontributor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcontributor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcontributorVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcontributorVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblrelation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrelation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblrelationVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrelationVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIDR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIDR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblIDRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIDRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldatestampR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldatestampR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldatestampRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldatestampRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblsetSpecR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblsetSpecR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblsetSpecRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblsetSpecRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitleR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTitleRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublisherR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublisherR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPublisherRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublisherRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubjecR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubjecR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubjecRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubjecRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldescriptionR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldescriptionR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldescriptionRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldescriptionRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldateR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldateR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbldateRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldateRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTypeR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTypeRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblidentifierR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblidentifierR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblidentifierRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblidentifierRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbllanguageR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbllanguageR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbllanguageRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbllanguageRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcoverageR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcoverageR As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcoverageRVal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcoverageRVal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOAILink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOAILink As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOAIHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOAIHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRULCap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRULCap As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtURLReSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtURLReSource As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblURLResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblURLResource As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lstURLResource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstURLResource As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkIdentify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkIdentify As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtfrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtfrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkListMetadataFormats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkListMetadataFormats As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtUntil control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUntil As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkListSets control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkListSets As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtmetadataPrefix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtmetadataPrefix As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkListIdentifiers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkListIdentifiers As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtidentifier control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtidentifier As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkListRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkListRecords As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSET control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSET As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkGetRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkGetRecord As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtresumptionToken control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtresumptionToken As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optParse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optParse As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optXML As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtVerb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVerb As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtShowInforReq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtShowInforReq As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtError As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtListSetsDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtListSetsDetail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtRecordDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRecordDetail As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtToken1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToken1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtToken2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToken2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtToken3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToken3 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
