'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class News_Add

        '''<summary>
        '''divThanhCong control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divThanhCong As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''DrLoai control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DrLoai As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txt_tieu_de control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_tieu_de As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lbl_luu_anh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_luu_anh As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbl_kq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_kq As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''F_Anh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents F_Anh As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''lbl_Anh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_Anh As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''CheckBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''CheckBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''Ch_iconNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Ch_iconNew As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txt_tom_tât control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_tom_tât As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Ch_HoTroSEO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Ch_HoTroSEO As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMeTaMoTa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMeTaMoTa As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtKeyword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeyword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txt_noi_dung control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_noi_dung As Global.CKEditor.NET.CKEditorControl

        '''<summary>
        '''P_HoTroSEO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents P_HoTroSEO As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnLuu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLuu As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
