'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class WILLInComing

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblTitleIllInComing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleIllInComing As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLabel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabel3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRequesterSymbol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequesterSymbol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtRequesterSymbol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRequesterSymbol As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNote1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNote1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRequestID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequestID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtRequestID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRequestID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRequestNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequestNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLabel5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabel5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRequesterName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRequesterName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtRequesterName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRequesterName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNote2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNote2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostDelivName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PostDelivXAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostDelivXAddr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivXAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivXAddr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPostDelivStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivStreet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivStreet As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPostDelivBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivBox As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPostDelivCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPostDelivCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPostDelivCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostDelivCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPostDelivCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostDelivCountry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPostDelivCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPostDelivCountry As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblEmailReplyAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmailReplyAddress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmailReplyAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailReplyAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNote3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNote3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAccountNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAccountNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAccountNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccountNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTelephone As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTelephone As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblEDelivMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEDelivMode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optFax As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optArielMIME control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optArielMIME As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optArielFTP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optArielFTP As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblEDelivTSAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEDelivTSAddr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEDelivTSAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEDelivTSAddr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEncodingSchema control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEncodingSchema As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlEncodingSchema control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEncodingSchema As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label26 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optLend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optLend As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCopy As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlItemType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblCopyrightCompliance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCopyrightCompliance As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optCCG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCCG As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optCCl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCCl As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblMedium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMedium As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlMedium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMedium As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Label31 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label31 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Label32 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label32 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cbxBillDelivEqualPostDeliv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbxBillDelivEqualPostDeliv As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblBillDelivName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivXAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivXAddr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivXAddr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivXAddr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivStreet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivStreet As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivBox As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivCity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBillDelivCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBillDelivCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBillDelivCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillDelivCountry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlBillDelivCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBillDelivCountry As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLabel40 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabel40 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPaymentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPaymentType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblMaxCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxCost As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMaxCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxCost As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCurrencyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrencyCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCurrencyCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCurrencyCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cbxReciprocalAgreement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbxReciprocalAgreement As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbxWillPayFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbxWillPayFee As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbxPaymentProvided control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbxPaymentProvided As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblLabel44 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLabel44 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCallNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCallNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCallNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCallNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPlaceOfPub control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPlaceOfPub As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPlaceOfPub control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPlaceOfPub As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublisher As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublisher As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSeriesTitleNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSeriesTitleNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSeriesTitleNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeriesTitleNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblVolumeIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVolumeIssue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtVolumeIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVolumeIssue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEdition As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEdition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEdition As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPubDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPubDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblComponentPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblComponentPubDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtComponentPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComponentPubDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblArticleAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtArticleAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtArticleAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblArticleTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblArticleTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtArticleTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtArticleTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPagination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPagination As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPagination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPagination As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNationalBibNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNationalBibNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNationalBibNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNationalBibNumber As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblISBN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblISBN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtISBN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtISBN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblISSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtISSN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOtherNumbers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOtherNumbers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOtherNumbers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOtherNumbers As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblVerification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVerification As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtVerification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtVerification As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPatronName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPatronName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPatronName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPatronName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPatronID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPatronID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPatronID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPatronID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNeedBeforeDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNeedBeforeDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNeedBeforeDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNeedBeforeDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPriority As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPriority As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''hidReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidReset As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidDublicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDublicate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btnSendRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSendRequest As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnDeleteRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDeleteRequest As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblMsgUpdateSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgUpdateSuccess As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgUpdateFail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgUpdateFail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDisIDRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisIDRequest As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDisAssignUD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisAssignUD As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDisTutorial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisTutorial As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgInvalidDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgInvalidDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgRequesterSymbol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgRequesterSymbol As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgRequestID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgRequestID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgEmailReply control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgEmailReply As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgEmailErr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgEmailErr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgRequest As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgNotNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgNotNum As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
