'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class WILLChapter

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblTitleIllChapter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleIllChapter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMainTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMainTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblChapterAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChapterAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtChapterAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChapterAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblChapterTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblChapterTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtChapterTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChapterTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBookName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBookName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBookName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBookName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblBookAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBookAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtBookAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBookAuthor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPublisher As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublisher As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPubDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPubDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblFoundAtLib control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFoundAtLib As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFoundAt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFoundAt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblOtherInfor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOtherInfor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOtherInfor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOtherInfor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblExpireDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpireDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtExpireDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpireDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkPubDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPubDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblCardNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCardNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtCardNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCardNum As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPassword As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblMaxCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxCost As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMaxCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxCost As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrency As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnPostRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPostRequest As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hidReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidReset As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblMsg1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg5 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg6 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsg7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg7 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgInvalidDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgInvalidDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgInvalidNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgInvalidNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgCreateSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgCreateSuccess As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMsgCreateFail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgCreateFail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDisOtherInfor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisOtherInfor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOver control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOver As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
