'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class WSavedFormat

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lnkRoot1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRoot1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lbspace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbspace As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkRoot2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRoot2 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''btnAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAction As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lbDocFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbDocFormat As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbDestination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbDestination As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optISBD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISBD As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optMARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optMARC As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optXML As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optDCXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDCXML As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optISO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISO As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optISOUNIMARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISOUNIMARC As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optISOUSMARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISOUSMARC As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optISOTVQG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISOTVQG As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optISONACESTID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISONACESTID As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optDesEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDesEmail As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''optDesFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDesFile As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optDesScreen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDesScreen As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''arrlistsaved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents arrlistsaved As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
