'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class WSavedListAction

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkRoot1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRoot1 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lbspace control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbspace As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkRoot2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRoot2 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lbspace1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbspace1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkRoot3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRoot3 As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblDownload1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDownload1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkGetIt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkGetIt As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblDownload2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDownload2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dtgSavedList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtgSavedList As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''hidAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidAction As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''arrlistsaved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents arrlistsaved As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
