'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OBrowse

        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader

        '''<summary>
        '''lrtDictionary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtDictionary As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''divSearchBrowse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSearchBrowse As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lrtPagination1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination1 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''divOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOrderBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ltrOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrOrderBy As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrList As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lrtPagination2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination2 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter

        '''<summary>
        '''spOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spCollection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCollection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spCatalogy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCatalogy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMsgNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMsgNotFound As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisher As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spKeyWord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spKeyWord As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSeries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSeries As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSubjectheading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSubjectheading As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisherYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherYear As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spDocType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDocType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spElectronicData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spElectronicData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFirstPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLastPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLastPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInputEmptyBrowse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInputEmptyBrowse As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spOrderAZ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderAZ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spOrderZA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderZA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spOrderAZRQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderAZRQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spOrderZARQ control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderZARQ As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidSearchBrowse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSearchBrowse As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidOrderBy As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''spDKCBInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDKCBInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSoDinhDanhInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSoDinhDanhInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisherInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMXG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMXG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spItemType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEDATA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEDATAContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATAContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPageLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPageLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSaveList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSaveList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spCancelList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCancelList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidTypeSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTypeSearch As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btSubmitBrowse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btSubmitBrowse As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseShowRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseShowRecord As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseOrderBy As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
