'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class ODetail
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''spFullDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFullDisplay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spISBDDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spISBDDisplay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spMARCDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMARCDisplay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spCataloguerDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCataloguerDisplay As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ltrViewFull control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrViewFull As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ltrViewISBD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrViewISBD As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ltrViewMARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrViewMARC As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ltrViewCataloger control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrViewCataloger As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''spRelationNone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRelationNone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spISSN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisher As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPhysicalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPhysicalInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPublisherInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEDATAContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATAContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEDATA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spItemType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spFree control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFree As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spBusy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBusy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spMap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMap As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spBarcodeInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBarcodeInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spMagazineInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMagazineInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAvailable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAvailable As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAddToMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAddToMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spInMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spKeyword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spKeyword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spSubjectHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSubjectHeading As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spDDC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDDC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNLM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNLM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spSeries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSeries As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRelatedWord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRelatedWord As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRegister control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRegister As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spReservation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spSumOnHold control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSumOnHold As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblMSG0 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG0 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG3 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG4 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG5R control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG5R As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMSG6H control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG6H As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hidItemID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidItemID As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidCopynumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCopynumber As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlLabel_FullRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel_FullRecord As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''hidView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidView As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidWord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidWord As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''raiseView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseView As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''raiseReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseReservation As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''raiseHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseHolding As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
