'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class OLogin
        
        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''spInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblShowText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShowText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''spSetPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSetPassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEmptyCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyCard As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEmptyPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyPassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hidEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidEmail As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''btnLoginForGoogle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLoginForGoogle As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
