'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OMap

        '''<summary>
        '''navHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents navHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divWelcome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divWelcome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lnkChangLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkChangLanguage As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''imgFlag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgFlag As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''ltrLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrLanguage As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lrtLibrary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtLibrary As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter

        '''<summary>
        '''spLanguageVietNamese control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguageVietNamese As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLanguageEnglish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguageEnglish As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spFinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFinish As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLibrary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
