'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class OMyList
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''lrtPagination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''ltrBookList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrBookList As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''spExport2File control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spExport2File As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spSend2Email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSend2Email As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPrint2List control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPrint2List As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spDelete2List control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDelete2List As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spItemType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEDATAContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATAContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spEDATA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spURL As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spISSN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPhysicalInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPhysicalInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPublisherInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNotFoundItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNotFoundItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRemoveMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRemoveMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hidCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidItem As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''raiseShowRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseShowRecord As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''raiseRemoveItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseRemoveItem As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
