'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class ONews
        
        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader
        
        '''<summary>
        '''h1News control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents h1News As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''LiteralListSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LiteralListSubject As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''SubjectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubjectName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ltrNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrNews As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''lrtPagination control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter
        
        '''<summary>
        '''hidCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hidIds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidIds As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''raiseShowRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseShowRecord As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
