'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class OPersonal
        
        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader
        
        '''<summary>
        '''h1Weblink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents h1Weblink As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ltrWeblink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrWeblink As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hidDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDOB As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTelephone As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidMobile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMobile As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidEmail As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidFacebook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidFacebook As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidDOBUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDOBUpdated As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidTelephoneUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTelephoneUpdated As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidMobileUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMobileUpdated As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidEmailUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidEmailUpdated As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidFacebookUpdated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidFacebookUpdated As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''imgPatron control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPatron As Global.System.Web.UI.HtmlControls.HtmlImage
        
        '''<summary>
        '''lblFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFullName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGender As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDOB As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCode As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblValidDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblValidDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblExpiredDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpiredDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblGroupName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGroupName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblFaculty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFaculty As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblGrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGrade As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClass As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTelephone As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMobile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMobile As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblFacebook control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFacebook As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtPasswordOld control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPasswordOld As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtPasswordNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPasswordNew As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtPasswordNewRe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPasswordNewRe As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btnUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblReserve control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReserve As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dgrReserve control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrReserve As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''lblReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReservation As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dgrReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrReservation As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''ckbCheckAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ckbCheckAll As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''divReservationDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divReservationDelete As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''btnReservationDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReservationDelete As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnOnHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnOnHolding As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnHolding As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''MainView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MainView As Global.System.Web.UI.WebControls.MultiView
        
        '''<summary>
        '''View1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents View1 As Global.System.Web.UI.WebControls.View
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''dgrOnHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrOnHolding As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''View2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents View2 As Global.System.Web.UI.WebControls.View
        
        '''<summary>
        '''dgrHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrHolding As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''lblHeaderNotePatron control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderNotePatron As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblNotePatron control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotePatron As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblILLRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblILLRequest As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dgrILLRequest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrILLRequest As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''lblInterestItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInterestItem As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hrfInterstItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hrfInterstItem As Global.System.Web.UI.WebControls.HyperLink
        
        '''<summary>
        '''dgrInterestItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgrInterestItem As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter
        
        '''<summary>
        '''spChooseDocument control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spChooseDocument As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblCheckOutDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCheckOutDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblCheckInDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCheckInDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblOverDueDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverDueDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbldelILL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldelILL As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRenew As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblOnHoldingB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOnHoldingB As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblNotRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotRenew As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblHour control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHour As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblGetBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGetBefore As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblLibaryName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLibaryName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPosition As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblHeaderReserve control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderReserve As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblHeaderReservation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderReservation As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblHeaderOnHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderOnHolding As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblHeaderHolding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeaderHolding As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''hdInterestObject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdInterestObject As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdInheritanceMap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdInheritanceMap As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdOpenedParentIDs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdOpenedParentIDs As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdAllwaysChecking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdAllwaysChecking As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdScrollTop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdScrollTop As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdUpdateFlage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdUpdateFlage As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''hdCirIDRenew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdCirIDRenew As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''btRenews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btRenews As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lbRenewSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbRenewSuccess As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbRenewError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbRenewError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbChangePassSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbChangePassSuccess As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbChangePassError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbChangePassError As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbPasswordOldNotTrue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbPasswordOldNotTrue As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbPasswordReNotTrue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbPasswordReNotTrue As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
