'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class ORegisterBooking
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader
        
        '''<summary>
        '''lbFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbFullName As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbPatronCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbPatronCode As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbEmail As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''RepeaterListRoom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RepeaterListRoom As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''ListTimesBusy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ListTimesBusy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ddlTypeRoom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTypeRoom As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtUses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUses As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtRequestOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRequestOther As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCount As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtListCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtListCode As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''GridViewHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridViewHistory As Global.System.Web.UI.WebControls.GridView
        
        '''<summary>
        '''hidDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDate As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidRoom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidRoom As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''hidTimes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTimes As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''lbMsgValidBusyTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbMsgValidBusyTime As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbMsgSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbMsgSuccess As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lbMsgValidCheckInTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbMsgValidCheckInTime As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''btnUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdate As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lbSubjectEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbSubjectEmail As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ContentMail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ContentMail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter
    End Class
End Namespace
