'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OSearchAdvanced

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader

        '''<summary>
        '''txtFieldValue1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue1 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlPrefix1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPrefix1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFieldName1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlOperator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOperator2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFieldValue2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue2 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlPrefix2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPrefix2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFieldName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlOperator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOperator3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFieldValue3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue3 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlPrefix3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPrefix3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFieldName3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''chkPublisherYear1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublisherYear1 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''ddlPublisherYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPublisherYear As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkPublisherYear2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublisherYear2 As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''txtPublisherYearFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublisherYearFrom As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtPublisherYearTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPublisherYearTo As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSort As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ltrLibrary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrLibrary As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrMaterialType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrMaterialType As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter

        '''<summary>
        '''spAddLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAddLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRemoveLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRemoveLimit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblMXG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMXG As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblISBN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblISBN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblISSN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblMSG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMSG As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbAllField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbAllField As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ValDocType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValDocType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lbTitleInDDL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbTitleInDDL As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblItemType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNamXuatBan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNamXuatBan As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDangTaiLieu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDangTaiLieu As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMsg As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblMsgNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsgNotFound As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hdLibraryIds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdLibraryIds As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hdMaterialType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdMaterialType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
