'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OSend2Email

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''spLblExport2file control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLblExport2file As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''spBackMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBackMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmailInValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmailInValid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
