'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OShow

        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader

        '''<summary>
        '''ltrBreadcrumbsInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrBreadcrumbsInResult As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrBreadcrumbsFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrBreadcrumbsFilter As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''divSearchInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSearchInResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lrtPagination1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination1 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''divOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOrderBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ltrOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrOrderBy As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrBookList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrBookList As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lrtPagination2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination2 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrDDC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrDDC As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrList As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter

        '''<summary>
        '''spSaveList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSaveList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spCancelList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCancelList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spOrderBy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPageLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPageLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMXG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMXG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spCatalogy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spCatalogy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEDATAContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATAContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEDATA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEDATA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spURL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMsgNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMsgNotFound As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spItemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spItemType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spISSN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spISSN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisher As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spKeyWord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spKeyWord As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSeries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSeries As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSubjectheading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSubjectheading As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spNLM control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNLM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spDDC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDDC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spElectronicData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spElectronicData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisherYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherYear As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spViewMore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spViewMore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spViewLess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spViewLess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRemoveFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRemoveFilter As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spTitleInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spTitleInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spDKCBInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDKCBInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSoDinhDanhInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSoDinhDanhInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPublisherInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPublisherInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFirstPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLastPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLastPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMyListTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyListTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spAddToMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAddToMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInfoSearchInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInfoSearchInResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInfoNotFound control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInfoNotFound As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spFilterFor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFilterFor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidTxtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTxtSearch As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSearch As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSearchEbooks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSearchEbooks As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidBrowseId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidBrowseId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidDicId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDicId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidDicName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDicName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidFilterStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidFilterStatus As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidOrderBy As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSearchInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSearchInResult As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidMutiLibrary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMutiLibrary As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSearchType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''raiseFilterInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseFilterInResult As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseFilter As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseShowRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseShowRecord As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseOrderBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseOrderBy As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''raiseDeleteFilterInResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseDeleteFilterInResult As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
