'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OTop

        '''<summary>
        '''smHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents smHeader As Global.System.Web.UI.ScriptManager

        '''<summary>
        '''navHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents navHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lnkChangLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkChangLanguage As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''imgFlag control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgFlag As Global.System.Web.UI.HtmlControls.HtmlImage

        '''<summary>
        '''ltrLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrLanguage As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''spLoginLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLoginLogout As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMyInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLibraryInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLibraryInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spNews control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNews As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spLinkSite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLinkSite As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''ltrLibraryList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrLibraryList As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''spSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSearchAdvance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSearchAdvance As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spSearchZ3950 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSearchZ3950 As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spBrowseByCollection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByCollection As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByTitle As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByAuthor As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByPublisherYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByPublisherYear As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByPublisher control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByPublisher As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseBySubjectHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseBySubjectHeading As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByKeyword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByKeyword As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spBrowseByDocType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spBrowseByDocType As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''spHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spHome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordByPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordByPrint As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordByEbooks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordByEbooks As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLibrary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLibrary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spAddToMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAddToMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidMyListIds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMyListIds As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''spMyListTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyListTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLblMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLblMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''spMyListDialog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyListDialog As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPatronInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPatronInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPopupLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPopupLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Span1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Span1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Span2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Span2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLblExport2file control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLblExport2file As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Label5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Span3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Span3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''spLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLogout As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spHello control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spHello As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spGuest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spGuest As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInputEmpty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInputEmpty As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLanguageVietNamese control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguageVietNamese As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLanguageEnglish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguageEnglish As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spWaiting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spWaiting As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmailValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmailValid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmailInValid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmailInValid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spLibraryLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLibraryLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''raiseLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseLogout As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
