'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OUserActive

        '''<summary>
        '''spInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''spEmptyCard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyCard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmptyIssuaDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyIssuaDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInvalidIssuaDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInvalidIssuaDate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmptyBirthday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyBirthday As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInvalidBirthday control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInvalidBirthday As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spEmptyPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spEmptyPassword As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInvalidPasswordLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInvalidPasswordLength As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spInvalidPasswordRule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spInvalidPasswordRule As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSetPassSuccess control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSetPassSuccess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spSetPasstFail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSetPasstFail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
