'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OViewerMagazineBrowseIssue

        '''<summary>
        '''browseList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents browseList As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''tbYearBrowseIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbYearBrowseIssue As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''imgList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgList As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''docId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidYear As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''raiseBrowseIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseBrowseIssue As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
