'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OViewerMagazineAllPages

        '''<summary>
        '''imgList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgList As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''hidMagId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMagId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidDocId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDocId As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidYear As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
