'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class OWebUseful
        
        '''<summary>
        '''sm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sm As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
        
        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader
        
        '''<summary>
        '''h1Weblink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents h1Weblink As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ltrWeblink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrWeblink As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter
        
        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAuthor As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFormat As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spLexile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLexile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spLanguage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLanguage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spGrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spGrade As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spPicture control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPicture As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spView As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spNoContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNoContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
