'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OZ3950

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''UHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UHeader1 As Global.eMicLibOPAC.WebUI.OPAC.UHeader

        '''<summary>
        '''txtzServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtzServer As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''lnkOServerList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkOServerList As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''txtZPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZPort As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtZDatabase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtZDatabase As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlFieldName1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFieldValue1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue1 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlOperator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOperator2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFieldName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFieldValue2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue2 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ddlOperator3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlOperator3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlFieldName3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFieldName3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFieldValue3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFieldValue3 As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''optMARC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optMARC As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optISBD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optISBD As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optSimple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optSimple As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''ddlLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLimit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''UFooter1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UFooter1 As Global.eMicLibOPAC.WebUI.OPAC.UFooter

        '''<summary>
        '''btnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''search control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents search As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
