'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC

    Partial Public Class OZ3950ServerList

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lrtPagination1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination1 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ltrServerList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrServerList As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lrtPagination2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lrtPagination2 As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''hidCurrentPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrentPage As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''spRecordItem control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spRecordOf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spRecordOf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spPreviousPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spPreviousPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spNextPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spNextPage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''raiseShowRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents raiseShowRecord As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
