'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace eMicLibOPAC.WebUI.OPAC
    
    Partial Public Class UHeader
        
        '''<summary>
        '''btnStudentLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnStudentLogin As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''btnLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogout As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''spFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spFullName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ltrAccountInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ltrAccountInfo As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''rdSearchOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdSearchOption As Global.System.Web.UI.HtmlControls.HtmlSelect
        
        '''<summary>
        '''spMyList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spMyList As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spAccountConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAccountConfig As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hidMyListIds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidMyListIds As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''spSearchAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSearchAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spSearchFulltext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spSearchFulltext As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hidUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidUser As Global.System.Web.UI.HtmlControls.HtmlInputHidden
        
        '''<summary>
        '''spAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spAccount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''spLogout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spLogout As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''ddlLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLabel As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
